spring:
  rabbitmq:
    listener:
      default-requeue-rejected: false
      retry:
        enabled: true
        initial-interval: 5000
        max-attempts: 3
        multiplier: 1.5
        max-interval: 10000
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    backoffPolicy:
      initialInterval: 500
      multiplier: 2.0
      maxInterval: 10000
  cloud:
    stream:
      bindings:
        booking_add_channel:
          input:
            destination: booking-add-queue
          contentType: application/json
  datasource:
    url: jdbc:h2:mem:bookings
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: schema_version
    validate-on-migrate: false
    url: jdbc:h2:mem:bookings
    password: sa
    user: sa
feign:
  hystrix:
    enabled: false